### ISSUE TITLE
Crashes on pre-Marshmallow

### ISSUE THREAD

**Issue by yuseiatlas** [Streamaxia/Android-Open-SDK#2]
The app crashes after the Splash screen on pre-Marshmallow devices, specifically Lollipop. It displays the following Log:
Process: com.streamaxia.opensdkdemo, PID: 17456
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.streamaxia.opensdkdemo/com.streamaxia.opensdkdemo.StreamActivity}: java.lang.RuntimeException: Fail to connect to camera service
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2695)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)
                                                                                at android.app.ActivityThread.access$900(ActivityThread.java:177)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:135)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5910)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
                                                                             Caused by: java.lang.RuntimeException: Fail to connect to camera service
                                                                                at android.hardware.Camera.<init>(Camera.java:550)
                                                                                at android.hardware.Camera.open(Camera.java:390)
                                                                                at com.streamaxia.android.b.g(Unknown Source)
                                                                                at com.streamaxia.android.b.a(Unknown Source)
                                                                                at com.streamaxia.android.b.c(Unknown Source)
                                                                                at com.streamaxia.android.CameraPreview.startCamera(Unknown Source)
                                                                                at com.streamaxia.opensdkdemo.StreamActivity.onCreate(StreamActivity.java:68)
                                                                                at android.app.Activity.performCreate(Activity.java:6178)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769) 
                                                                                at android.app.ActivityThread.access$900(ActivityThread.java:177) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:135) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5910) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by chelemen-razvan** [comment]
Fixed
