### ISSUE TITLE
Null Pointer Exceptions on sample app

### ISSUE THREAD

**Issue by yuseiatlas** [Streamaxia/Android-Open-SDK#3]
The sample apps sometimes crashes after giving permissions to camera causing the following log:
10-09 09:41:40.194 403-403/com.streamaxia.opensdkdemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.streamaxia.opensdkdemo, PID: 403
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.streamaxia.opensdkdemo/com.streamaxia.opensdkdemo.StreamActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:223)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7223)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
                                                                            at com.streamaxia.android.b.getSupportedPreviewSizes(Unknown Source)
                                                                            at com.streamaxia.android.e.a(Unknown Source)
                                                                            at com.streamaxia.android.StreamaxiaPublisher.getSupportedPictureSizes(Unknown Source)
                                                                            at com.streamaxia.opensdkdemo.StreamActivity.setStreamerDefaultValues(StreamActivity.java:137)
                                                                            at com.streamaxia.opensdkdemo.StreamActivity.onCreate(StreamActivity.java:68)
                                                                            at android.app.Activity.performCreate(Activity.java:6877)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:223) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7223) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
Devices I've tested and showed this:
Nexus 5 (Marshmallow)
Nexus 5X (Nougat)
Samsung GALAXY A5 (Marshmallow)
Samsung GALAXY S7 Edge (Nougat)
Samsung GALAXY J7

**Comment by chelemen-razvan** [comment]
Fixed
