### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: dlopen failed:

### ISSUE THREAD

**Issue by prashantgunit** [Streamaxia/Android-Open-SDK#6]
Hi there,
I implemented this sample code it is working fine with up to android lollipop version. when i run this sample in nougat version it gives following error : -

java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.mysample.sample-1/lib/x86/libenc.so: has text relocations
        at java.lang.Runtime.loadLibrary0(Runtime.java:989)
        at java.lang.System.loadLibrary(System.java:1530)
        at com.streamaxia.android.Encoder.<clinit>(Encoder.java:698)
        at com.streamaxia.android.RTMPPublisher.setEncoderHandler(RTMPPublisher.java:439)
        at com.streamaxia.android.StreamaxiaPublisher.setEncoderHandler(StreamaxiaPublisher.java:134)
        at com.eclipseeducation.eclipseeducation.CameraSample.onCreate(CameraSample.java:141)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by chelemen-razvan** [comment]
Hello,

What device are you using?

Thank you,
Razvan

**Comment by prashantgunit** [comment]
I am using it in my emulator

**Comment by chelemen-razvan** [comment]
Ok. The library its not supposed to work in the emulator since it does not have a camera. But we will try to find a solution for the crash.

**Comment by prashantgunit** [comment]
ok. But it is working on the emulator if i change target version to 22. My emulator is accessing webcam of my laptop. let me check on device and i will let you know.

**Comment by prashantgunit** [comment]
i just tried on my oppo A57 device now it give following error 

```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.eclipseeducation.eclipseeducation/com.mysample.sample.CameraSample}: java.lang.RuntimeException: Fail to connect to camera service
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2545)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2605)
        at android.app.ActivityThread.access$1100(ActivityThread.java:165)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:179)
        at android.app.ActivityThread.main(ActivityThread.java:5730)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)
     Caused by: java.lang.RuntimeException: Fail to connect to camera service
        at android.hardware.Camera.<init>(Camera.java:580)
        at android.hardware.Camera.open(Camera.java:390)
        at com.streamaxia.android.CameraView.openCamera(CameraView.java:244)
        at com.streamaxia.android.CameraView.startCamera(CameraView.java:151)
        at com.streamaxia.android.CameraPreview.startCamera(CameraPreview.java:129)
        at com.eclipseeducation.eclipseeducation.CameraSample.onCreate(CameraSample.java:145)
        at android.app.Activity.performCreate(Activity.java:6439)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2498)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2605) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:165) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:179) 
        at android.app.ActivityThread.main(ActivityThread.java:5730) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681) 
```

**Comment by chelemen-razvan** [comment]
You’ll have to go to settings->app->name_of_your app and give it camera and mic permissions.

**Comment by prashantgunit** [comment]
Hi chelemen razvan,
Please tell me that how can i reduce video file size stored 
in sdcard.

**Comment by chelemen-razvan** [comment]
Hello,

The video stored is the same with the video you stream, if you stream at a lower resolution or at a lower bitrate the file saved locally will be smaller. There is no way to control the file size independently. Hope this helps!

Thank you,
Razvan

**Comment by prashantgunit** [comment]
Thanks and i think you can close this issue because i run my sample on nougat device it is working fine. But on nougat emulator it is crashing so may be it is emulator error
