### ISSUE TITLE
start Camera Exception

### ISSUE THREAD

**Issue by MohamedHarmoush** [Streamaxia/Android-Open-SDK#7]
02-05 11:36:55.299 6863-6863/harmoush.com.fyberfairbiddemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: harmoush.com.fyberfairbiddemo, PID: 6863
    java.lang.RuntimeException: Unable to start activity ComponentInfo{harmoush.com.fyberfairbiddemo/harmoush.com.demo.MainActivity}: java.lang.NullPointerException: Attempt to write to field 'int com.streamaxia.android.Encoder.l' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to write to field 'int com.streamaxia.android.Encoder.l' on a null object reference
        at com.streamaxia.android.e$1.a(Unknown Source:16)
        at com.streamaxia.android.b.g(Unknown Source:58)
        at com.streamaxia.android.b.c(Unknown Source:5)
        at com.streamaxia.android.CameraPreview.startCamera(Unknown Source:2)
        at harmoush.com.demo.MainActivity.initUi(MainActivity.java:206)
        at harmoush.com.demo.MainActivity.onCreate(MainActivity.java:137)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by JTMaher2** [comment]
I am having this same problem, except for "int com.streamaxia.android.Encoder.b" instead of "int com.streamaxia.android.Encoder.l." Does anyone have any advice about how to get around this?

**Comment by nelson-glauber** [comment]
It's not the same problem, but I guess it's similar...
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.nio.ByteBuffer[] android.media.MediaCodec.getInputBuffers()' on a null object reference
        at com.streamaxia.android.Encoder.a(Unknown Source:10)
        at com.streamaxia.android.Encoder.a(Unknown Source:58)
        at com.streamaxia.android.e$a.a(Unknown Source:96)
        at com.streamaxia.android.b$a.run(Unknown Source:36)
        at java.lang.Thread.run(Thread.java:919) 
```
Any suggestion?
